events/urls.py
from django.urls import path 
from . import views



app_name = 'events'
urlpatterns = [
    path('',views.List_Events, name='list'),
    path('add_event/', views.Add_Event, name='add_event'),
    path('delete_event/<int:event_id>/',views.Delete_Event, name='delete_event')

]

family_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('events/',include('events.urls')),
    path('messages/', include('custom_messages.urls')),
    path('family_messages/', include('family_messages.urls')),
    path('about_us/', include('about_us.urls')),
    path('ancestry/', include('ancestry.urls')),
    path('family_media/', include('family_media.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomePage,name='home'),
    path('posts',views.Posts, name='posts'),
    path('add_post/', views.AddPost, name='add_post'),
    path('family_tree/', views.family_tree, name='family_tree'),
]

events/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class FamilyEvents(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    content = models.TextField()
    image = models.ImageField(upload_to='photos/',blank=True, null=True)
    video = models.FileField(upload_to='videos/', blank=True, null=True)
    happening_date = models.DateTimeField()

    def __str__(self):
        return self.name

events/forms.py
from django import forms
from .models import FamilyEvents


class AddEventForm(forms.ModelForm):
    class Meta:
        model = FamilyEvents
        fields = [
            'name',
            'content',
            'image',
            'video',
            'happening_date',
        ]
        labels = {
            'name':'Name of the Event',
            'content':'Event Details',
            'image':'Upload any related Photos',
            'video':'Upload any related Videos',
            'happening_date':'Happening Date',
                  }
        
        widgets = {'content':forms.Textarea(attrs={'cols':80}),
                   'happening_date':forms.DateInput(attrs={'type':'date'})}

events/views.py
from django.shortcuts import render, redirect
from .models import FamilyEvents
from .forms import AddEventForm
from django .utils import timezone

# Create your views here.
def List_Events(request):
    events = FamilyEvents.objects.all().order_by('-happening_date')
    return render(request, 'events/events.html', context={'events':events})

def Add_Event(request):
    if request.method == 'POST':
        form = AddEventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.user = request.user
            event.save()
            return redirect('events:list')
    else:
        form = AddEventForm()
    return render(request, 'events/add_event.html', {'form': form})

def Delete_Event(request, event_id):
    event = FamilyEvents.objects.get(id=event_id)
    event.delete()
    return redirect('events:list')



        

events/templates/events/add_event.html
{% extends 'home/base.html' %}

{% block title %}Add an Event{% endblock title %}

{% block content %}
    <div class="container">
        <div class="form-container">
            <h2>Add Your Event</h2>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="id_name">{{ form.name.label }}</label>
                    {{ form.name }}
                </div>

                <div class="form-group">
                    <label for="id_content">{{ form.content.label }}</label>
                    {{ form.content }}
                </div>

                <div class="form-group">
                    <label for="id_image">{{ form.image.label }}</label>
                    {{ form.image }}
                </div>

                <div class="form-group">
                    <label for="id_video">{{ form.video.label }}</label>
                    {{ form.video }}
                </div>

                <div class="form-group">
                    <label for="id_happening_date">{{ form.happening_date.label }}</label>
                    {{ form.happening_date }}
                </div>

                <button type="submit" class="submit-btn">Submit</button>
            </form>
        </div>
    </div>
{% endblock content %}

events/templates/events/events.html
{% extends 'home/base.html' %}

{% block title %}Events{% endblock title %}

{% block content %}
  <h2 id="event-title">Events Happening Soon</h2>
  <a id="add-event-link" href="{% url 'events:add_event' %}">Add your Event</a>
  {% for event in events %}
    <h4 id="event-head">{{ event.name }}</h4>
    <p id="event">{{ event.content }}</p>
    {% if event.image %}
    <img id="event-image" src="{{ event.image.url }}" alt="{{ event.title }}" style="max-width: 100%; height: auto;">
    {% endif %}
    {% if event.video %}
      <video id="event-video" width="320" height="240" controls>
          <source src="{{ event.video.url }}" type="video/mp4">
          Your browser does not support the video tag.
      </video>
    {% endif %}
    <a id="delete-event-link" href="{% url 'events:delete_event' event.id %}">Delete The Event</a>
    {% empty %}
      <p>No events available at this moment</p>

  {% endfor %}
  


{% endblock content %}