about_us/urls.py
from django.urls import path
from . import views

app_name = 'about_us'
urlpatterns = [
    path('about_us/', views.history, name='history'),
    path('about_us/add_history', views.add_history, name='add_history'),
    
]

accounts/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'accounts'
urlpatterns = [
    path('login/',LoginView.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(), name='logout')
]

ancestry/urls.py
from django.urls import path
from . import views

app_name = 'ancestry'
urlpatterns = [
    path('ancestry/', views.ancestry, name='ancestry'),
    path('ancestry/endit_ancestry/', views.edit_ancestry, name='edit_ancestry'),
    path('ancestry/add_ancestry/', views.add_ancestry, name='add_ancestry'),


    
]

events/urls.py
from django.urls import path 
from . import views



app_name = 'events'
urlpatterns = [
    path('',views.List_Events, name='list'),
    path('add_event/', views.Add_Event, name='add_event'),
    path('delete_event/<int:event_id>/',views.Delete_Event, name='delete_event')

]

family_media/urls.py
from django.urls import path
from . import views

app_name = 'family_media'
urlpatterns = [
    path('family_media/', views.media, name='family_media'),
    path('add_media/', views.add_media, name='add_media'),
]

family_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('events/',include('events.urls')),
    path('messages/', include('custom_messages.urls')),
    path('family_messages/', include('family_messages.urls')),
    path('about_us/', include('about_us.urls')),
    path('ancestry/', include('ancestry.urls')),
    path('family_media/', include('family_media.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomePage,name='home'),
    path('posts',views.Posts, name='posts'),
    path('add_post/', views.AddPost, name='add_post'),
    path('family_tree/', views.family_tree, name='family_tree'),
]

about_us/models.py
from django.db import models

# Create your models here.
class OurHistory(models.Model):
    subject = models.CharField(max_length=100, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to='images/')
    video = models.FileField(blank=True, null=True, upload_to='videos/')

    def __str__(self):
        return f"{self.subject}'s History"

about_us/forms.py
from django import forms
from .models import OurHistory

class AddHistory(forms.ModelForm):
    class Meta:
        model = OurHistory
        fields = ['subject', 'content', 'image', 'video']
        labels = {
            'subject':'Name of the Person',
            'content':'History Content',
            'image':'Any related image',
            'video':'Any related video'
            

        }
        widgets = {'content':forms.Textarea(attrs={'col':40, 'rows':10})}

about_us/views.py
from django.shortcuts import render, redirect
from .models import OurHistory
from .forms import AddHistory

# Create your views here.
def history(request):
    histories = OurHistory.objects.all()
    context = {'histories':histories}
    return render(request,'about_us/history.html', context)
    
def add_history(request):
    if request.method == 'POST':
        form = AddHistory(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('about_us:history')
    else:
        form = AddHistory()
    context = {'form':form}
    return render(request, 'about_us/add_history.html', context)   
    

about_us/templates/about_us/add_history.html
{% extends 'home/base.html' %}

{% block title %}Add Bio{% endblock title %}

{% block content %}
  <div class="add-bio">
    <h2>Add Biography</h2>

    {% if user.is_authenticated %}
      <p>Welcome, {{ user.username }}!</p>
    {% else %}
      <p>Please log in to add history.</p>
    {% endif %}

    {% if form.errors %}
      <div class="error">
        <p>Please correct the errors below:</p>
        {{ form.errors }}
      </div>
    {% endif %}
    <form id="add-bio-form" action="{% url 'about_us:add_history' %}" method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Add History</button>
    </form>
  </div>


{% endblock content %}

about_us/templates/about_us/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}Ngabo Ezaaya{% endblock title %}
    </title>
</head><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ngabo Ezaaya</title>
    <link href="static/css/home.css" rel="stylesheet"/>
</head>
<body>
    <header>
        <button id="menu-toggle">☰ Menu</button>
        <div id="title">
            <img id="logo" src="static/images/image4.png" alt="Logo"/>
            <h1>BAIJUKURU BA NGABO IZAAYA</h1> 
        </div>
    </header>

    <nav id="main-nav">
        <div id="nav-one">
            <a href="{% url 'home:home' %}">Home</a>
            <a href="{% url 'about_us:history' %}">About Us</a>
            <a href="{% url 'ancestry:ancestry' %}">Ancestry</a>
            <a href="#">Family Trees</a>
            <a href="{% url 'events:list' %}">Events</a>
            <a href="{% url 'family_media:family_media' %}">Gallery</a>
        </div>
        <div id="nav-two">
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">Logout</a>
            <a href="{% url 'custom_messages:inbox' %}">Messages</a>
            <a href="{% url 'family_messages:family' %}">Talk Group</a>
        {% else %}
                <a href="{% url 'accounts:login' %}">Login</a>
                <a href="{% url 'accounts:register' %}">Register</a>
        {% endif %}
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <footer>
        <div class="contacts">
            <div id="chair">
                <h4>Chairman</h4>
            </div>
            <div id="sec">
                <h4>Secretary</h4>
            </div>
            <div id="treasurer">
                <h4>Treasurer</h4>
            </div>
        </div>
        <div class="feedback">
            <h4>feedback</h4>
        </div>
    </footer>
    <script src="static/js/home.js"></script>
</body>
    
</body>
</html>

about_us/templates/about_us/history.html
{% extends 'home/base.html' %}

{% block title %}Our History{% endblock title %}


  {% block content %}
  
  <div class="hist">
    <h2>THE NGABO IZAAYA GREAT PERSONALITIES</h2>

    {% for hist in histories %}
      <h3>{{ hist.subject }}</h3>
      {% if hist.image %}
      <img src="{{ hist.image.url }}" height="300px" width="300px">
      {% endif %}
      {% if hist.video %}
      <video>
          <source src="{{ post.video.url }}" type="video/mp4">
      </video>
      {% endif %}
      <p>{{ hist.content }}</p>
    {% endfor %}
    {% if user.is_authenticated %}
       <a href="{% url 'about_us:add_history' %}">Add New Biography</a>
    {% endif %}
  </div>






{% endblock content %}